spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/blogdb
    username: postgres
    password: Pasca789@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  security:
    bearerAuth: [ ]
    user:
      name: Marie
      password: Marie@78



  data:
    mongodb:
      uri: mongodb://localhost:27017/blogdb
      database: blogdb




springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT




server:
  port: 8080

